# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nessad
tagline:          'Infrastructure Engineer'
description:      'A blog about my tech journey'
url:              https://nessadc.com 
baseurl:          /

author:
  name:           'Nessad Choudhury'
  url:            https://twitter.com/nessad_c

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nessadc

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
